management:

  endpoint:
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        health: /admin/health
        metrics: /admin/metrics
        prometheus: /metrics